# Generated by Django 4.1 on 2023-11-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmailRecipient',
        ),
    ]
